### ISSUE TITLE
doesn't work in sublime text 3

### ISSUE THREAD

**Issue by ghost** [mattbanks/dotfiles-syntax-highlighting-st2#23]
Steps to recreate the issue
1. install "Dotfiles Syntax Highlighting" package with Package Control
2. open `~/.zshrc`
3. "Plain text" highlighter is used

:(

**Comment by kevinSuttle** [comment]
Not the case for me. I think my issue is that the plugin is set to only show for certain file names. Here are mine. https://github.com/kevinSuttle/dotfiles

**Comment by mattbanks** [comment]
Right, the plugin looks for the actual file names of the dotfiles. If you want to customize for your own set of dotfiles that get synlinked or copied, you'll have to manually add those to the language preferences list in ST3.

**Comment by wzup** [comment]
Doesn't work at all in ST3.
