### ISSUE TITLE
Doesn't work in ST3. No option is syntax list, no auto highlight

### ISSUE THREAD

**Issue by wzup** [mattbanks/dotfiles-syntax-highlighting-st2#33]
How does the plugin work?
After installation it just does nothing. No syntax highlight, and there is no even option in syntax list. Reload ST3 doesn't help

**Comment by mattbanks** [comment]
The plugin sets the syntax mode to `Shell-Unix-Generic` for all file extensions listed in https://github.com/mattbanks/dotfiles-syntax-highlighting-st2/blob/master/Shell-Unix-Generic.sublime-settings.

I just installed a fresh copy of ST3 (dev build 3109) in a VM and installed the extension. After restarting ST3, I opened my dotfiles folder and the files were opened with the proper Shell-Unix-Generic format. Can you let me know if you see any errors in the Console or are trying to open file extensions that aren't included in the plugin?

**Comment by diegorv** [comment]
**Stable Build 3103**

Not working for me too... 

But in Sublime Console doesn't have any error.

How I can help debug this problem? Maybe a problem with Sublime version? :/

**Comment by diegorv** [comment]
<img width="438" alt="screen shot 2016-05-02 at 5 33 55 pm" src="https://cloud.githubusercontent.com/assets/24455/14967105/13b70150-108c-11e6-8855-0b38a30796af.png">

Yep, maybe this is a problem with Sublime version.

**Comment by diegorv** [comment]
Still not working with 3111 version... :/

**Comment by mattbanks** [comment]
Hmm, not totally sure what changed that's causing it to not get applied properly in the latest ST3 builds. I'm tied up with a bunch of projects right now, so I'm not sure when I'll get a chance to take a look into it.

**Comment by gaoryrt** [comment]
not working with build 3114

**Comment by vmuriart** [comment]
It's working for me on 3126.

It might have broken after the migration from [tmlanguage to sublime-syntax](https://github.com/sublimehq/Packages/commit/585e986e926be96c1d1bd886497cc0f409097c51#diff-eb14d7bb0305685ad9fa251e5b0c9623) which first showed up on [3103](http://www.sublimetext.com/blog/articles/sublime-text-3-build-3103)

**Comment by mattbanks** [comment]
Glad it's working now for you! I'm going to close this issue. If anyone else is still having problems, feel free to re-open it!

**Comment by wzup** [comment]
Not working.
Build `3143`

**Comment by mattbanks** [comment]
Just opened here in a fresh install of ST3 stable (3143). After installing package control and this package, my dotfiles repo opened up the proper file types. I wonder if there's a conflicting package?

**Comment by codingforpleasure** [comment]
Unfortunately it's not working for me with **.zshrc** file,
apparently for .bashrc it works flawlessly.

I'm using **Sublime Text Build 3176**.

and my **Package Control.sublime-settings** file holds:
```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Dotfiles Syntax Highlighting",
		"LuaComplete",
		"MarkdownPreview",
		"Package Control",
		"sublimelint",
		"SublimeLinter",
		"SublimeLinter-contrib-bashate",
		"SublimeLinter-shellcheck",
		"SummitLinter"
	]
}
```

Any suggestions how to handle/fix this issue?
