### ISSUE TITLE
Support for zsh autocomplete script (_func)

### ISSUE THREAD

**Issue by cgjosephlee** [mattbanks/dotfiles-syntax-highlighting-st2#39]
zsh autocomplete files are named as `_func` which `func`refers to the command name. And the header is:
```
#compdef function
...
```
The syntax is same with other zsh config files, but a scope is needed for sublime text to identify.

**Comment by mattbanks** [comment]
I'm not sure we want to generalize all files prefixed with `__` and having no extension as using shell script as the type. That could be something that you setup locally instead of adding it to the plugin here. I'll let other people weigh in though.

**Comment by cgjosephlee** [comment]
The better way would be add something like `"first_line_match": ["^#\\s*compdef"]` to apply syntax, but I'm not sure how does it work in `.sublime-settings` files.

Another similar package [SyntaxManager](https://github.com/randy3k/SyntaxManager) might provide some insights.

**Comment by mattbanks** [comment]
That's probably suited for that plugin. Here we're just setting the file extensions for use.

If you want to modify the plugin and submit a PR, I can take a look. I'm not using ST3 anymore, so I'm not doing any active development here.

**Comment by cgjosephlee** [comment]
Thank you, I'll give it a try.
