### ISSUE TITLE
No syntax highlighting for .vimrc

### ISSUE THREAD

**Issue by cheshire137** [mattbanks/dotfiles-syntax-highlighting-st2#8]
I installed the package, it's there in my Sublime Text 2/Packages directory on OS X, but opening a .vimrc, it still loads it as Plain Text.  I see no new options in the Syntax menu for highlighting the file.

**Comment by evandrocoan** [comment]
Someone known where I can find a `.vimrc` syntax highlighting?

**Comment by evandrocoan** [comment]
I think I found this one: https://github.com/RobRoseKnows/vimscript-sublime

**Comment by evandrocoan** [comment]
I also found this one to be more complete: https://github.com/SalGnt/Sublime-VimL
